CREATE TABLE IF NOT EXISTS T_ITEM (F_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, F_NAME VARCHAR(90) NOT NULL, F_STATUS VARCHAR(20) NOT NULL, F_DELETED BOOLEAN NOT NULL) ENGINE InnoDB
CREATE TABLE IF NOT EXISTS T_USER (F_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, F_USERNAME VARCHAR(80) NOT NULL, F_ROLE_ID NOT NULL, F_PASSWORD VARCHAR(30) NOT NULL, F_DELETED BOOLEAN NOT NULL, FOREIGN KEY (F_ROLE_ID) REFERENCES T_ROLE (F_ID)) ENGINE InnoDB
CREATE TABLE IF NOT EXISTS T_ROLE (F_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, F_NAME VARCHAR(40) NOT NULL) ENGINE InnoDB
